### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by minatafreshi** [jimmyheller/tech-immigrants#7]
There is a problem in the `Netherlands` category about RTL format.
@amin-setayeshfar 
Fixed in [PR](https://github.com/jimmyheller/tech-immigrants/pull/8#issue-1023003650) .

**Comment by amin-setayeshfar** [comment]
> There is a problem in the `Netherlands` category about RTL format. @amin-setayeshfar

Do you mean the very problem you fixed the other night? if so, I believe you can link your pull request to this issue just to make sure it won't exist after merging
